apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app2
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/thangphan3000/hello-argocd-and-gitops.git
    targetRevision: HEAD
    path: environments/staging/app2
  destination:
    server: https://kubernetes.default.svc
    namespace: bar
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
